### ISSUE TITLE
Enable serial console by default

### ISSUE THREAD

**Issue by hubpav** [bigclownlabs/bc-raspbian#2]
Serial console should be enabled by default. This can be explicitly done in raspi-config tool. This request is based on customer's feedback.

**Comment by jirutka** [comment]
It’s a bit complicated with serial port on RPi 3: [Configuring The GPIO Serial Port On Raspbian Jessie Including Pi 3](http://spellfoundry.com/2016/05/29/configuring-gpio-serial-port-raspbian-jessie-including-pi-3). There’s no one right configuration that works for all. When you change this, other people may complain that it does not work for them. What is more common, connecting some devices via serial port or a console?

Why he needs/wants console over serial port? Isn’t is that he needs it just to configure network, so he can eventually connect via Ethernet/Wi-Fi and SSH?

* * *

@blavka had a very good idea how to provide very _simple_ (i.e. no mobile applications etc.) way how to preconfigure network: put configuration file for network to FAT part of the SD card and let system load it from it.

It’s also useful to write the current IP address (if obtained from DHCP) to the console as “issue” message. I have [script for that](https://gist.github.com/jirutka/3a72ebf1906a50dbaba8c2264e16ffb3), but eventually forgot to add it to the image.

Also it’s a good idea to write the current IP address to a file on the SD card, for the case that you don’t have right cable to connect RPi to monitor (this actually happened even to me).

**Comment by hubpav** [comment]
What I want is to have by default the same configuration as if you launch `sudo raspi-config` tool, go to `Advanced Options` and tick `Serial` option to have it enabled. This will give you getty going on the serial port as well as kernel messages with 115200 8N1 configuration.

It is not just about network setup but instant access to the machine without re-configuring your desktop host or you even do not want to tweak the RPi's network connection.

Again this is a request from our customer and person who uses RPi heavily and does a lot of presentation. He is not telling me the first time. I just forgot to pass the message when you had been configuring Raspbian image initially and now the same person reminded me.

Regarding @blavka idea - I kind of like it but this is a separate feature which will take some time to implement and we will have to consider security matter since I do not want just "somebody" who get physical access to the machine to plug in the USB stick and reconfigure its network interface...

Thank you.

**Comment by muhlpachr** [comment]
Just reminder, anybody who get physical access to the SD can reconfigure RPi network interfaces (do anything on RPi generally).
Filesystem type (FAT vs ext) could be "only" security by obscurity matter.
Even MSW desktop can mount and modify ext4 fs on SD plugged in USB stick.

**Comment by jirutka** [comment]
> What I want is to have by default the same configuration as if you launch `sudo raspi-config` tool, go to `Advanced Options` and tick `Serial` option to have it enabled.

I don’t have such option in `Advanced Options`; it’s in `Interfacing Options`, so I assume that it was just renamed.

I’ve implemented the requested change in #3.

> I do not want just "somebody" who get physical access to the machine to plug in the USB stick and reconfigure its network interface...

As Michal wrote, when “sombody” get physical access to RPi or just SD card, (s)he can do anything with it anyway. As I know, the described features don’t have any real security implications.

Note: `/boot` partition is vFAT (so no permissions), but it’s mounted with fmask/dmask 0022 by default, so unprivileged user/process can’t write to it.

**Comment by jirutka** [comment]
Another idea: RPi has audio output, we can use it to literally _tell_ the user IP address after boot. 😸 I’ve found that some people already did it.

**Comment by hubpav** [comment]
Thanks for implementing the change. I have already asked the person who requested this change to validate this feature.
